const FormFieldsInfo = {
  instructionInfo: {
    heading: "Instructions",
    description: "Read the below instructions carefully:",
    instructions: [
      "Fill out all fields accurately.",
      "Upload necessary documents.",
      "Ensure contact information is up-to-date.",
      "Click Submit to finalize your registration.",
    ],
    checkboxStatus: {
      show: true,
      label: "I have read the instructions carefully.",
      errorMsg: "Please check the box.",
    },
  },
  headerInfo: {
    heading: "JAYPEE'S GOT LATENT",
  },
  footerInfo: {
    contactus: {
      heading: "For any query please contact:",
      person1: {
        name: "Yash Mittal",
        Phno: "+91 8570940287",
      },
      person2: {
        name: "Shantanu Pandey",
        Phno: "+91 9026152678",
      },
    },
  },
  formInfo: [
    {
      heading: "Name",
      name: "entry.name",
      required: true,
      type: "text",
      placeholder: "Enter your name",
      errorMsg: "Name is required.",
    },
    {
      heading: "Email",
      name: "entry.email",
      required: true,
      type: "email",
      placeholder: "Enter your email",
      errorMsg: "Email is required.",
      regex: "^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$",
    },
    {
      heading: "Phone",
      name: "entry.phone",
      required: true,
      type: "text",
      placeholder: "Enter your phone number",
      errorMsg: "Phone number is required.",
      regex: "^[0-9]{10}$",
    },
    {
      heading: "Branch",
      name: "entry.branch",
      required: true,
      type: "radio",
      labels: [
        "Computer Science",
        "Information Technology",
        "Electronics & Communication",
        "EE VLSI",
        "ECE Adv Com.",
        "Mathematics & Computing",
        "BCA",
        "BBA",
        "MBA",
        "Others",
      ],
      otherKey: ".other_option_response",
      errorMsg: "Please select your branch.",
    },
    {
      heading: "Batch",
      name: "entry.batch",
      required: true,
      type: "text",
      placeholder: "Enter your batch",
      errorMsg: "Batch is required.",
      // regex: "^[0-9]{10}$",
    },
    {
      heading: "Are you single (relationship status)?",
      name: "entry.relationship_status",
      required: true,
      type: "radio",
      labels: ["Yes", "No"],
      otherKey: ".other_option_response",
      errorMsg: "Above field is required.",
    },
    {
      heading: "Do you have any sibling?",
      name: "entry.sibling",
      required: true,
      type: "radio",
      labels: ["Yes", "No"],
      otherKey: ".other_option_response",
      errorMsg: "Above field is required.",
    },

    {
      heading: "What would you do if your gender was reversed for one day?",
      name: "entry.gender_reveresed",
      required: true,
      type: "textarea",
      placeholder: "write your answer here ...",
      errorMsg: "Above field is required.",
    },
    {
      heading: "Most daring thing you have done?",
      name: "entry.daring_thing",
      required: true,
      type: "textarea",
      placeholder: "write your answer here ...",
      errorMsg: "Above field is required.",
    },
    {
      heading: "Your biggest achievement till date.",
      name: "entry.biggest_achievement",
      required: true,
      type: "textarea",
      placeholder: "write your answer here ...",
      errorMsg: "Above field is required.",
    },
    {
      heading: "Goals in your life (apart from academics).",
      name: "entry.life_goals",
      required: true,
      type: "textarea",
      placeholder: "write your answer here ...",
      errorMsg: "Above field is required.",
    },
  ],
};

export default FormFieldsInfo;
